"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---- 环境变量 ----
# 生产部署所有可变项都从环境变量读取，本地开发可放 .env（见 .env.example）。
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: 生产必须通过 DJANGO_SECRET_KEY 注入，默认值仅供本地开发。
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-fa6(^n_-6#o&m)&1no*5q^jx(khzsfg3ot-esvhxf%2b*h8k&8',
)

DEBUG = env.bool('DJANGO_DEBUG', default=False)

# 逗号分隔，例如 DJANGO_ALLOWED_HOSTS=design.example.com,10.0.0.5
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Django 4+ 要求带 scheme，例如 https://design.example.com
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])

if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'design',
    'talkbot',
    'users',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.BrowserSecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend_dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 优先读 DATABASE_URL（生产用 PostgreSQL：postgres://user:pass@host:5432/dbname）；
# 未配置时回落到本地 SQLite，保证开发流程与既有 db.sqlite3 不变。
DATABASE_URL = env('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {'default': env.db_url_config(DATABASE_URL)}
    DATABASES['default']['CONN_MAX_AGE'] = env.int('DJANGO_CONN_MAX_AGE', default=60)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # 多窗口并行生图会有多个请求同时写库，
            # 放宽锁等待时间，配合 WAL 模式（见 design/apps.py）避免 database is locked
            'OPTIONS': {'timeout': 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(env('DJANGO_STATIC_ROOT', default=str(BASE_DIR / 'staticfiles')))

# 单端口部署：Vue 构建产物挂到 /static/spa/（与 vite.config.js 的 base 对齐）
STATICFILES_DIRS = [
    ('spa', BASE_DIR / 'frontend_dist'),
]

# WhiteNoise：DEBUG=False 时由应用进程直接托管 /static/，
# 即使前面没有 nginx 也不会白屏（有 nginx 时 nginx 命中在前，不会走到这里）。
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30

MEDIA_URL = '/media/'
# 生产用挂载卷，例如 DJANGO_MEDIA_ROOT=/data/media，避免容器重建丢失效果图
MEDIA_ROOT = Path(env('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media')))

# 上传毛坯照片上限 10MB，留出 multipart 余量
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', default=26214400)

# ---- 反向代理与安全 ----
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    # 仅在确实走 HTTPS 时开启，否则 HTTP 部署会被重定向循环挡死
    SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=False)
    SESSION_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)
    CSRF_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=86400)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True,
    )
    SECURE_HSTS_PRELOAD = env.bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'SAMEORIGIN'

CORS_ALLOW_ALL_ORIGINS = DEBUG

# SimpleUI removes Django's stock clickjacking middleware at app startup; the
# custom security-header middleware plus nginx are covered by config tests.
# HSTS preload remains deliberately off during the short max-age rollout.
SILENCED_SYSTEM_CHECKS = ['security.W002', 'security.W021']

# DRF cost controls must be shared by all Gunicorn workers. Bare-process installs
# fall back to a high-capacity file cache; production Compose explicitly injects
# the Redis backend and location below.
CACHE_BACKEND = env(
    'DJANGO_CACHE_BACKEND',
    default=(
        'django.core.cache.backends.locmem.LocMemCache'
        if DEBUG else 'django.core.cache.backends.filebased.FileBasedCache'
    ),
)
CACHE_LOCATION = env(
    'DJANGO_CACHE_LOCATION',
    default=('arch-ai-local-cache' if DEBUG else '/tmp/arch-ai-cache'),
)
CACHE_OPTIONS = {}
if CACHE_BACKEND.endswith(('FileBasedCache', 'LocMemCache')):
    CACHE_OPTIONS = {
        'MAX_ENTRIES': env.int('DJANGO_CACHE_MAX_ENTRIES', default=50000),
        'CULL_FREQUENCY': env.int('DJANGO_CACHE_CULL_FREQUENCY', default=10),
    }
CACHES = {
    'default': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': CACHE_LOCATION,
        'TIMEOUT': 60 * 60 * 24,
        'OPTIONS': CACHE_OPTIONS,
    },
}

# 户型图上传限制（PRD 5.1）
FLOORPLAN_MAX_UPLOAD_MB = 20
FLOORPLAN_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'application/pdf']

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Production has two trusted hops: the TLS/CDN edge and the Compose nginx.
    # The origin port must only accept traffic from that edge (see deploy SOP).
    'NUM_PROXIES': env.int('DJANGO_NUM_PROXIES', default=2),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_register_ip': env('AUTH_REGISTER_IP_RATE', default='10/day'),
        'auth_login_ip': env('AUTH_LOGIN_IP_RATE', default='60/hour'),
        'auth_login_target': env('AUTH_LOGIN_TARGET_RATE', default='10/hour'),
        'auth_verification_ip': env('AUTH_VERIFICATION_IP_RATE', default='30/hour'),
        'auth_verification_target': env('AUTH_VERIFICATION_TARGET_RATE', default='5/hour'),
        'auth_password_reset_ip': env('AUTH_PASSWORD_RESET_IP_RATE', default='10/hour'),
        'auth_password_reset_target': env('AUTH_PASSWORD_RESET_TARGET_RATE', default='5/hour'),
        'design_render_user': env('DESIGN_RENDER_USER_RATE', default='12/hour'),
        'design_render_ip': env('DESIGN_RENDER_IP_RATE', default='30/hour'),
        'design_sales_user': env('DESIGN_SALES_USER_RATE', default='10/day'),
        'design_sales_ip': env('DESIGN_SALES_IP_RATE', default='30/day'),
        'talkbot_session': env('TALKBOT_SESSION_RATE', default='10/day'),
        'talkbot_message': env('TALKBOT_MESSAGE_RATE', default='30/hour'),
        'talkbot_convert': env('TALKBOT_CONVERT_RATE', default='10/day'),
        'talkbot_ip': env('TALKBOT_IP_RATE', default='120/hour'),
    },
}

# TalkBot ships in deterministic rule mode. Enable the external text model only
# after the production knowledge base and provider configuration are verified.
TALKBOT_LLM_ENABLED = env.bool('TALKBOT_LLM_ENABLED', default=False)
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY', default='')
DEEPSEEK_API_BASE = env('DEEPSEEK_API_BASE', default='https://api.deepseek.com')
DEEPSEEK_MODEL = env('DEEPSEEK_MODEL', default='deepseek-v4-flash')
DEEPSEEK_TIMEOUT_SECONDS = env.float('DEEPSEEK_TIMEOUT_SECONDS', default=25.0)
DEEPSEEK_MAX_RETRIES = env.int('DEEPSEEK_MAX_RETRIES', default=1)

# ---- 用户系统 ----
# 开发默认打印到控制台；生产在 .env 配置 SMTP（见 .env.example）。
EMAIL_BACKEND = env(
    'DJANGO_EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('DJANGO_EMAIL_HOST', default='')
EMAIL_PORT = env.int('DJANGO_EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('DJANGO_EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('DJANGO_EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('DJANGO_EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('DJANGO_EMAIL_USE_SSL', default=False)
DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL', default='noreply@example.com')
PASSWORD_RESET_TIMEOUT_MINUTES = env.int('DJANGO_PASSWORD_RESET_TIMEOUT_MINUTES', default=30)

# ---- 短信验证码 ----
# console：只打印验证码到日志，用于本地联调；webhook：POST 到短信网关。
SMS_BACKEND = env('SMS_BACKEND', default='console')
SMS_WEBHOOK_URL = env('SMS_WEBHOOK_URL', default='')
SMS_WEBHOOK_TIMEOUT = env.int('SMS_WEBHOOK_TIMEOUT', default=10)
SMS_CODE_LENGTH = env.int('SMS_CODE_LENGTH', default=6)
SMS_CODE_TTL_MINUTES = env.int('SMS_CODE_TTL_MINUTES', default=5)
SMS_MAX_ATTEMPTS = env.int('SMS_MAX_ATTEMPTS', default=5)

# 邮箱验证码
EMAIL_CODE_LENGTH = env.int('EMAIL_CODE_LENGTH', default=6)
EMAIL_CODE_TTL_MINUTES = env.int('EMAIL_CODE_TTL_MINUTES', default=5)
EMAIL_CODE_MAX_ATTEMPTS = env.int('EMAIL_CODE_MAX_ATTEMPTS', default=5)

# 持久登录令牌（App 端关闭后可恢复登录）
REMEMBER_TOKEN_TTL_DAYS = env.int('REMEMBER_TOKEN_TTL_DAYS', default=30)

# ---- 支付与额度 ----
# mock：本地联调，不发起真实扣款，前端可点击「模拟支付」完成入账；
# live：按下方渠道配置发起真实收款。上线前请务必切换为 live 并配置密钥。
PAYMENT_MODE = env('PAYMENT_MODE', default='mock')
PAYMENT_FREE_CREDITS = env.int('PAYMENT_FREE_CREDITS', default=5)
# 静态收款码模式：没有支付 API 时使用。下单后展示微信/支付宝收款码，
# 用户扫码付款后由后台人工确认入账；不发起渠道 API 调用。
PAYMENT_QR_MODE = env.bool('PAYMENT_QR_MODE', default=False)

# Stripe（国际信用卡）。Stripe 与国内微信/支付宝共用一套套餐，
# 若套餐为 CNY，会按 PAYMENT_STRIPE_EXCHANGE_RATE 折算为目标币种。
PAYMENT_STRIPE_SECRET_KEY = env('PAYMENT_STRIPE_SECRET_KEY', default='')
PAYMENT_STRIPE_PUBLIC_KEY = env('PAYMENT_STRIPE_PUBLIC_KEY', default='')
PAYMENT_STRIPE_WEBHOOK_SECRET = env('PAYMENT_STRIPE_WEBHOOK_SECRET', default='')
PAYMENT_STRIPE_CURRENCY = env('PAYMENT_STRIPE_CURRENCY', default='usd')
PAYMENT_STRIPE_EXCHANGE_RATE = env.float('PAYMENT_STRIPE_EXCHANGE_RATE', default=0.14)
PAYMENT_STRIPE_TAX_CODE = env('PAYMENT_STRIPE_TAX_CODE', default='txcd_10000000')
PAYMENT_STRIPE_API_VERSION = env('PAYMENT_STRIPE_API_VERSION', default='2025-03-31.basil')

# 微信支付（Native 扫码，v3）。密钥请使用 PEM 格式文本。
PAYMENT_WECHAT_APP_ID = env('PAYMENT_WECHAT_APP_ID', default='')
PAYMENT_WECHAT_MCH_ID = env('PAYMENT_WECHAT_MCH_ID', default='')
PAYMENT_WECHAT_SERIAL_NO = env('PAYMENT_WECHAT_SERIAL_NO', default='')
PAYMENT_WECHAT_PRIVATE_KEY = env('PAYMENT_WECHAT_PRIVATE_KEY', default='')
PAYMENT_WECHAT_API_V3_KEY = env('PAYMENT_WECHAT_API_V3_KEY', default='')
PAYMENT_WECHAT_PLATFORM_PUBLIC_KEY = env('PAYMENT_WECHAT_PLATFORM_PUBLIC_KEY', default='')
PAYMENT_WECHAT_NOTIFY_URL = env('PAYMENT_WECHAT_NOTIFY_URL', default='')

# 支付宝（当面付/扫码）。密钥请使用 PEM 格式文本。
PAYMENT_ALIPAY_APP_ID = env('PAYMENT_ALIPAY_APP_ID', default='')
PAYMENT_ALIPAY_PRIVATE_KEY = env('PAYMENT_ALIPAY_PRIVATE_KEY', default='')
PAYMENT_ALIPAY_PUBLIC_KEY = env('PAYMENT_ALIPAY_PUBLIC_KEY', default='')
PAYMENT_ALIPAY_SELLER_ID = env('PAYMENT_ALIPAY_SELLER_ID', default='')
PAYMENT_ALIPAY_NOTIFY_URL = env('PAYMENT_ALIPAY_NOTIFY_URL', default='')

# 可浏览 API 页面只在开发环境暴露
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer'
    )

# ---- 日志：容器内统一输出到 stdout，交给 docker logs / 日志采集 ----
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('DJANGO_LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'design': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---- SimpleUI 后台配置 ----
SIMPLEUI_HOME_TITLE = '梦想家 控制台'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False          # 关闭匿名统计上报
SIMPLEUI_STATIC_OFFLINE = True     # 使用本地静态资源，不依赖 CDN
SIMPLEUI_LOGO = None
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# 自定义左侧菜单，按 PRD 功能域组织
SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['梦想家', '工作流', '谈单机器人', '用户管理', '支付管理'],
    'dynamic': False,
    'menus': [
        {
            'name': '梦想家',
            'icon': 'fas fa-couch',
            'models': [
                {'name': '业主', 'icon': 'fas fa-user-tie', 'url': '/admin/design/owner/'},
                {'name': '房屋项目', 'icon': 'fas fa-home', 'url': '/admin/design/project/'},
                {'name': '设计方案', 'icon': 'fas fa-drafting-compass', 'url': '/admin/design/designscheme/'},
                {'name': '效果图任务', 'icon': 'fas fa-image', 'url': '/admin/design/renderjob/'},
                {'name': '家具商品', 'icon': 'fas fa-chair', 'url': '/admin/design/furniture/'},
                {'name': '设计师', 'icon': 'fas fa-user-pen', 'url': '/admin/design/designer/'},
                {'name': '服务商/施工队', 'icon': 'fas fa-store', 'url': '/admin/design/serviceprovider/'},
                {'name': '线索留资', 'icon': 'fas fa-address-book', 'url': '/admin/design/lead/'},
                {'name': '用户需求收集', 'icon': 'fas fa-clipboard-list', 'url': '/admin/design/customerrequirement/'},
                {'name': '我的家报告书', 'icon': 'fas fa-file-alt', 'url': '/admin/design/homereport/'},
                {'name': '我的家项目订单', 'icon': 'fas fa-shopping-cart', 'url': '/admin/design/homeorder/'},
                {'name': '订单详情', 'icon': 'fas fa-file-invoice', 'url': '/admin/design/orderdetail/'},
                {'name': '生成配置(API)', 'icon': 'fas fa-key', 'url': '/admin/design/generationconfig/'},
                {'name': 'Prompt 控制模块', 'icon': 'fas fa-sliders-h', 'url': '/admin/design/promptmodule/'},
            ],
        },
        {
            'name': '工作流',
            'icon': 'fas fa-project-diagram',
            'models': [
                {'name': '生图工作流', 'icon': 'fas fa-sitemap', 'url': '/admin/design/renderworkflow/'},
                {'name': '工作流步骤', 'icon': 'fas fa-list-ol', 'url': '/admin/design/workflowstep/'},
            ],
        },
        {
            'name': '谈单机器人',
            'icon': 'fas fa-robot',
            'models': [
                {'name': '谈单会话', 'icon': 'fas fa-comments', 'url': '/admin/talkbot/conversation/'},
                {'name': '谈单客户画像', 'icon': 'fas fa-user-tag', 'url': '/admin/talkbot/customerprofile/'},
                {'name': '谈单工作流', 'icon': 'fas fa-route', 'url': '/admin/talkbot/talkworkflow/'},
                {'name': '谈单工作流步骤', 'icon': 'fas fa-list-ol', 'url': '/admin/talkbot/talkstep/'},
                {'name': '谈单知识库', 'icon': 'fas fa-book', 'url': '/admin/talkbot/knowledgebase/'},
                {'name': '谈单知识文档', 'icon': 'fas fa-file-alt', 'url': '/admin/talkbot/knowledgedocument/'},
            ],
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users-cog',
            'models': [
                {'name': '用户', 'icon': 'fas fa-user', 'url': '/admin/auth/user/'},
                {'name': '用户组', 'icon': 'fas fa-users', 'url': '/admin/auth/group/'},
                {'name': '用户资料', 'icon': 'fas fa-id-card', 'url': '/admin/users/userprofile/'},
                {'name': '重置令牌', 'icon': 'fas fa-key', 'url': '/admin/users/passwordresettoken/'},
                {'name': '持久登录令牌', 'icon': 'fas fa-ticket-alt', 'url': '/admin/users/remembertoken/'},
                {'name': '短信验证码', 'icon': 'fas fa-sms', 'url': '/admin/users/smsverificationcode/'},
                {'name': '邮箱验证码', 'icon': 'fas fa-envelope-open-text', 'url': '/admin/users/emailverificationcode/'},
            ],
        },
        {
            'name': '支付管理',
            'icon': 'fas fa-wallet',
            'models': [
                {'name': '充值套餐', 'icon': 'fas fa-tags', 'url': '/admin/payments/pricingplan/'},
                {'name': '收款订单', 'icon': 'fas fa-file-invoice-dollar', 'url': '/admin/payments/paymentorder/'},
                {'name': '额度流水', 'icon': 'fas fa-exchange-alt', 'url': '/admin/payments/credittransaction/'},
            ],
        },
    ],
}
