"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---- 环境变量 ----
# 生产部署所有可变项都从环境变量读取，本地开发可放 .env（见 .env.example）。
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: 生产必须通过 DJANGO_SECRET_KEY 注入，默认值仅供本地开发。
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-fa6(^n_-6#o&m)&1no*5q^jx(khzsfg3ot-esvhxf%2b*h8k&8',
)

DEBUG = env.bool('DJANGO_DEBUG', default=False)

# 逗号分隔，例如 DJANGO_ALLOWED_HOSTS=design.example.com,10.0.0.5
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Django 4+ 要求带 scheme，例如 https://design.example.com
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])

if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'design',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend_dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 优先读 DATABASE_URL（生产用 PostgreSQL：postgres://user:pass@host:5432/dbname）；
# 未配置时回落到本地 SQLite，保证开发流程与既有 db.sqlite3 不变。
DATABASE_URL = env('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {'default': env.db_url_config(DATABASE_URL)}
    DATABASES['default']['CONN_MAX_AGE'] = env.int('DJANGO_CONN_MAX_AGE', default=60)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # 多窗口并行生图会有多个请求同时写库，
            # 放宽锁等待时间，配合 WAL 模式（见 design/apps.py）避免 database is locked
            'OPTIONS': {'timeout': 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(env('DJANGO_STATIC_ROOT', default=str(BASE_DIR / 'staticfiles')))

# 单端口部署：Vue 构建产物挂到 /static/spa/（与 vite.config.js 的 base 对齐）
STATICFILES_DIRS = [
    ('spa', BASE_DIR / 'frontend_dist'),
]

# WhiteNoise：DEBUG=False 时由应用进程直接托管 /static/，
# 即使前面没有 nginx 也不会白屏（有 nginx 时 nginx 命中在前，不会走到这里）。
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30

MEDIA_URL = '/media/'
# 生产用挂载卷，例如 DJANGO_MEDIA_ROOT=/data/media，避免容器重建丢失效果图
MEDIA_ROOT = Path(env('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media')))

# 效果图存在 MEDIA_ROOT，DEBUG=False 后 Django 默认不再托管 /media/。
# 有 nginx 时保持 False（由 nginx 直接发文件）；单容器直跑时设为 True 由 Django 兜底托管。
SERVE_MEDIA_FILES = env.bool('DJANGO_SERVE_MEDIA', default=False)

# 上传毛坯照片上限 10MB，留出 multipart 余量
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', default=26214400)

# ---- 反向代理与安全 ----
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    # 仅在确实走 HTTPS 时开启，否则 HTTP 部署会被重定向循环挡死
    SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=False)
    SESSION_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)
    CSRF_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'

CORS_ALLOW_ALL_ORIGINS = DEBUG

# 户型图上传限制（PRD 5.1）
FLOORPLAN_MAX_UPLOAD_MB = 20
FLOORPLAN_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'application/pdf']

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# ---- 用户系统 ----
# 开发默认打印到控制台；生产在 .env 配置 SMTP（见 .env.example）。
EMAIL_BACKEND = env(
    'DJANGO_EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('DJANGO_EMAIL_HOST', default='')
EMAIL_PORT = env.int('DJANGO_EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('DJANGO_EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('DJANGO_EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('DJANGO_EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL', default='noreply@example.com')
PASSWORD_RESET_TIMEOUT_MINUTES = env.int('DJANGO_PASSWORD_RESET_TIMEOUT_MINUTES', default=30)

# 可浏览 API 页面只在开发环境暴露
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer'
    )

# ---- 日志：容器内统一输出到 stdout，交给 docker logs / 日志采集 ----
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('DJANGO_LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'design': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---- SimpleUI 后台配置 ----
SIMPLEUI_HOME_TITLE = 'Arch_AI Platform 控制台'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False          # 关闭匿名统计上报
SIMPLEUI_STATIC_OFFLINE = True     # 使用本地静态资源，不依赖 CDN
SIMPLEUI_LOGO = None
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# 自定义左侧菜单，按 PRD 功能域组织
SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['Arch_AI Platform', '工作流', '用户管理'],
    'dynamic': False,
    'menus': [
        {
            'name': 'Arch_AI Platform',
            'icon': 'fas fa-couch',
            'models': [
                {'name': '业主', 'icon': 'fas fa-user-tie', 'url': '/admin/design/owner/'},
                {'name': '房屋项目', 'icon': 'fas fa-home', 'url': '/admin/design/project/'},
                {'name': '设计方案', 'icon': 'fas fa-drafting-compass', 'url': '/admin/design/designscheme/'},
                {'name': '效果图任务', 'icon': 'fas fa-image', 'url': '/admin/design/renderjob/'},
                {'name': '家具商品', 'icon': 'fas fa-chair', 'url': '/admin/design/furniture/'},
                {'name': '设计师', 'icon': 'fas fa-user-pen', 'url': '/admin/design/designer/'},
                {'name': '服务商/施工队', 'icon': 'fas fa-store', 'url': '/admin/design/serviceprovider/'},
                {'name': '线索留资', 'icon': 'fas fa-address-book', 'url': '/admin/design/lead/'},
                {'name': '订单详情', 'icon': 'fas fa-file-invoice', 'url': '/admin/design/orderdetail/'},
                {'name': '生成配置(API)', 'icon': 'fas fa-key', 'url': '/admin/design/generationconfig/'},
            ],
        },
        {
            'name': '工作流',
            'icon': 'fas fa-project-diagram',
            'models': [
                {'name': '生图工作流', 'icon': 'fas fa-sitemap', 'url': '/admin/design/renderworkflow/'},
                {'name': '工作流步骤', 'icon': 'fas fa-list-ol', 'url': '/admin/design/workflowstep/'},
            ],
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users-cog',
            'models': [
                {'name': '用户', 'icon': 'fas fa-user', 'url': '/admin/auth/user/'},
                {'name': '用户组', 'icon': 'fas fa-users', 'url': '/admin/auth/group/'},
                {'name': '用户资料', 'icon': 'fas fa-id-card', 'url': '/admin/users/userprofile/'},
                {'name': '重置令牌', 'icon': 'fas fa-key', 'url': '/admin/users/passwordresettoken/'},
            ],
        },
    ],
}
