# Generated by Django 5.0.6 on 2026-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_credits',
            field=models.PositiveIntegerField(default=5, help_text='每位用户一次性赠送的免费生成次数，消耗完毕后开始使用充值额度', verbose_name='免费生成额度'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchased_credits',
            field=models.PositiveIntegerField(default=0, help_text='通过支付套餐购买的生成次数', verbose_name='充值生成额度'),
        ),
    ]
