# Generated by Django 5.0.6 on 2026-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_free_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('purpose', models.CharField(choices=[('bind', '绑定手机'), ('login', '验证码登录')], max_length=10, verbose_name='用途')),
                ('code_hash', models.CharField(max_length=64, verbose_name='验证码摘要')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='失败次数')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', 'used_at'], name='users_smsve_phone_23905f_idx')],
            },
        ),
    ]
