# Generated by Django 5.0.6 on 2026-08-19 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='令牌摘要')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='注销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remember_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '持久登录令牌',
                'verbose_name_plural': '持久登录令牌',
                'ordering': ('-created_at',),
            },
        ),
    ]
