# Generated by Django 5.0.6 on 2026-08-24 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0016_normalize_stored_media_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='知识库名称')),
                ('category', models.CharField(choices=[('script', '话术'), ('case', '案例'), ('quote', '报价'), ('craft', '工艺/环保'), ('faq', '常见问题'), ('objection', '异议处理')], max_length=20, verbose_name='分类')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '谈单知识库',
                'verbose_name_plural': '谈单知识库',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='会话标题')),
                ('stage', models.CharField(choices=[('icebreak', '破冰'), ('discovery', '需求挖掘'), ('matching', '方案匹配'), ('objection', '异议处理'), ('closing', '促单'), ('ordered', '已下单'), ('follow_up', '后续维护')], default='icebreak', max_length=20, verbose_name='销售阶段')),
                ('status', models.CharField(choices=[('active', '进行中'), ('converted', '已转化'), ('closed', '已结束')], default='active', max_length=12, verbose_name='会话状态')),
                ('last_action', models.CharField(blank=True, max_length=20, verbose_name='最近动作')),
                ('summary', models.TextField(blank=True, verbose_name='会话摘要')),
                ('workflow_log', models.JSONField(blank=True, default=list, verbose_name='最近执行轨迹')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkbot_conversation', to='design.homeorder', verbose_name='转化订单')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkbot_conversations', to='design.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkbot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '谈单会话',
                'verbose_name_plural': '谈单会话',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='称呼')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('community', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='建筑面积(㎡)')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='重点空间')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='意向风格')),
                ('situation', models.TextField(blank=True, verbose_name='客户处境')),
                ('household', models.CharField(blank=True, max_length=120, verbose_name='家庭结构')),
                ('has_kids', models.BooleanField(blank=True, null=True, verbose_name='有孩子')),
                ('kids_age', models.CharField(blank=True, max_length=50, verbose_name='孩子年龄')),
                ('has_elderly', models.BooleanField(blank=True, null=True, verbose_name='有老人同住')),
                ('pets', models.CharField(blank=True, max_length=80, verbose_name='宠物')),
                ('income_tier', models.CharField(blank=True, max_length=30, verbose_name='消费能力档位')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算下限(元)')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算上限(元)')),
                ('decision_power', models.CharField(blank=True, max_length=80, verbose_name='决策关系')),
                ('recent_events', models.JSONField(blank=True, default=list, verbose_name='近期事件')),
                ('desired_timeline', models.CharField(blank=True, max_length=80, verbose_name='期望入住时间')),
                ('emotion', models.CharField(choices=[('neutral', '平静'), ('anxious', '焦虑'), ('hesitant', '犹豫'), ('expectant', '期待'), ('distrustful', '不信任'), ('defensive', '防御'), ('satisfied', '满意')], default='neutral', max_length=20, verbose_name='当前情绪')),
                ('emotion_trace', models.JSONField(blank=True, default=list, verbose_name='情绪轨迹')),
                ('persona_type', models.CharField(choices=[('unknown', '待判断'), ('rational', '理性'), ('emotional', '感性'), ('impulsive', '冲动'), ('cautious', '谨慎')], default='unknown', max_length=20, verbose_name='决策类型')),
                ('pain_points', models.JSONField(blank=True, default=list, verbose_name='核心顾虑')),
                ('trust_score', models.PositiveSmallIntegerField(default=20, verbose_name='信任度')),
                ('intent_score', models.PositiveSmallIntegerField(default=20, verbose_name='意向度')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='待补信息')),
                ('consent_to_contact', models.BooleanField(default=False, verbose_name='同意联系')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='talkbot.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': '谈单客户画像',
                'verbose_name_plural': '谈单客户画像',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='向量（预留）')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='talkbot.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '谈单知识文档',
                'verbose_name_plural': '谈单知识文档',
                'ordering': ('priority', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '机器人'), ('system', '系统')], max_length=12, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('intent', models.CharField(blank=True, max_length=40, verbose_name='识别意图')),
                ('emotion', models.CharField(blank=True, max_length=30, verbose_name='识别情绪')),
                ('question_asked', models.CharField(blank=True, max_length=40, verbose_name='本轮询问字段')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='结构化信息')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='talkbot.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': '谈单消息',
                'verbose_name_plural': '谈单消息',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TalkWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='工作流名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='匹配标签')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认工作流')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('stop_on_error', models.BooleanField(default=False, verbose_name='步骤失败即终止')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkbot_workflows', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '谈单工作流',
                'verbose_name_plural': '谈单工作流',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TalkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='执行顺序')),
                ('kind', models.CharField(choices=[('intake', '接收输入'), ('emotion', '情绪识别'), ('intent', '意图识别'), ('profile_update', '更新画像'), ('stage_judge', '阶段判断'), ('strategy_plan', '策略决策'), ('rag_retrieve', '知识检索'), ('llm_generate', '生成回复'), ('guard', '安全合规'), ('output', '输出'), ('log', '记录轨迹')], max_length=30, verbose_name='步骤类型')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='步骤名称')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('continue_on_error', models.BooleanField(default=True, verbose_name='失败仍继续')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='talkbot.talkworkflow', verbose_name='所属工作流')),
            ],
            options={
                'verbose_name': '谈单工作流步骤',
                'verbose_name_plural': '谈单工作流步骤',
                'ordering': ('workflow', 'order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='talkbot_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='talkbot_message_time_idx'),
        ),
    ]
