# Generated by Django 5.0.6 on 2026-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0002_seed_talkbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_processing',
            field=models.BooleanField(default=False, editable=False, verbose_name='正在生成回复'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='开始生成时间'),
        ),
    ]
