# Generated by Django 5.0.6 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0003_conversation_is_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(
                blank=True,
                help_text='同一轮的用户消息与机器人回复共享该标识，用于请求幂等。',
                max_length=64,
                verbose_name='客户端消息标识',
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(
                condition=~models.Q(client_id=''),
                fields=('conversation', 'role', 'client_id'),
                name='talkbot_message_client_unique',
            ),
        ),
    ]
