# Generated by Django 5.0.6 on 2026-08-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='套餐名称')),
                ('slug', models.SlugField(unique=True, verbose_name='套餐编码')),
                ('credits', models.PositiveIntegerField(help_text='购买后增加的生成次数', verbose_name='生成额度')),
                ('price_cents', models.PositiveIntegerField(help_text='以最小货币单位计，如 19.90 元存 1990', verbose_name='价格（分）')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=3, verbose_name='币种')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='套餐说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '充值套餐',
                'verbose_name_plural': '充值套餐',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, editable=False, help_text='系统自动生成，如 PAY20260817123000A1B2C3', max_length=40, unique=True, verbose_name='订单编号')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('wechat', '微信支付'), ('alipay', '支付宝')], max_length=10, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=12, verbose_name='状态')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='实付金额（分）')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='购买额度')),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='如 Stripe Session ID / 微信 out_trade_no / 支付宝 trade_no', max_length=120, verbose_name='渠道交易号')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='渠道响应')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.pricingplan', verbose_name='充值套餐')),
            ],
            options={
                'verbose_name': '收款订单',
                'verbose_name_plural': '收款订单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grant', '免费额度'), ('purchase', '充值入账'), ('consume', '生成消耗'), ('refund', '失败退回')], max_length=10, verbose_name='流水类型')),
                ('credits', models.IntegerField(help_text='正数为入账，负数为消耗', verbose_name='额度变动')),
                ('balance_after', models.PositiveIntegerField(default=0, verbose_name='变动后总额度')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.paymentorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '额度流水',
                'verbose_name_plural': '额度流水',
                'ordering': ('-created_at',),
            },
        ),
    ]
