# Generated by Django 5.0.6 on 2026-08-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payment_note',
            field=models.CharField(blank=True, help_text='静态收款码模式下，用户填写的支付流水/联系方式，供后台人工核对', max_length=200, verbose_name='支付备注'),
        ),
    ]
