# Generated by Django 5.0.6 on 2026-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentorder_payment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='kind',
            field=models.CharField(choices=[('grant', '免费额度'), ('purchase', '充值入账'), ('consume', '生成消耗'), ('refund', '失败退回'), ('adjust', '管理员调整')], max_length=10, verbose_name='流水类型'),
        ),
    ]
