# Generated by Django 5.0.6 on 2026-08-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='风格定位')),
                ('budget_tier', models.CharField(choices=[('economy', '经济'), ('quality', '品质'), ('premium', '高端')], default='quality', max_length=10, verbose_name='预算档位')),
                ('layout', models.TextField(blank=True, verbose_name='空间布局说明')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='亮点')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='风险提示')),
                ('suitable_for', models.CharField(blank=True, max_length=100, verbose_name='适合人群')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算下限(元)')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算上限(元)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='schemes/', verbose_name='风格图')),
                ('bom', models.JSONField(blank=True, default=list, verbose_name='BOM初版')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('is_favorited', models.BooleanField(default=False, verbose_name='已收藏')),
                ('buildable_checked', models.BooleanField(default=False, verbose_name='已做可施工校验')),
                ('assumptions', models.TextField(blank=True, verbose_name='方案假设与预算口径')),
            ],
            options={
                'verbose_name': '设计方案',
                'verbose_name_plural': '设计方案',
                'ordering': ('project', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('community', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('house_status', models.CharField(blank=True, choices=[('new', '新房'), ('old', '旧房翻新'), ('rent', '出租房')], max_length=10, verbose_name='房屋状态')),
                ('preference_tags', models.JSONField(blank=True, default=list, verbose_name='偏好标签')),
            ],
            options={
                'verbose_name': '业主',
                'verbose_name_plural': '业主',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(choices=[('design', '设计团队'), ('construction', '施工队'), ('supplier', '供应商')], max_length=20, verbose_name='类型')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='资质')),
                ('cases', models.JSONField(blank=True, default=list, verbose_name='案例')),
                ('quote_range', models.CharField(blank=True, max_length=100, verbose_name='报价区间')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('response_speed', models.CharField(blank=True, max_length=50, verbose_name='响应速度')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='保证金(元)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '服务商',
                'verbose_name_plural': '服务商',
                'ordering': ('-rating', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='项目名称')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('community', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('floorplan', models.ImageField(blank=True, null=True, upload_to='floorplans/', verbose_name='户型图')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='面积(㎡)')),
                ('room_structure', models.JSONField(blank=True, default=dict, verbose_name='房间结构')),
                ('requirement_summary', models.JSONField(blank=True, default=dict, verbose_name='需求摘要')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算下限(元)')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算上限(元)')),
                ('status', models.CharField(choices=[('draft', '建档中'), ('recognized', '识别完成'), ('requirement', '需求澄清'), ('scheme', '方案生成'), ('lead', '已留资'), ('signed', '已签约')], default='draft', max_length=20, verbose_name='项目状态')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='design.owner', verbose_name='业主')),
            ],
            options={
                'verbose_name': '房屋项目',
                'verbose_name_plural': '房屋项目',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('community', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('new', '待分配'), ('assigned', '已分配'), ('contacted', '已联系'), ('closed', '已关闭')], default='new', max_length=10, verbose_name='状态')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='design.designscheme', verbose_name='意向方案')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='design.project', verbose_name='房屋项目')),
            ],
            options={
                'verbose_name': '线索留资',
                'verbose_name_plural': '线索留资',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='designscheme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='design.project', verbose_name='房屋项目'),
        ),
    ]
