# Generated by Django 5.0.6 on 2026-08-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='头衔')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('styles', models.JSONField(blank=True, default=list, verbose_name='擅长风格')),
                ('years', models.PositiveIntegerField(default=0, verbose_name='从业年限')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='designers/', verbose_name='头像')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '设计师',
                'verbose_name_plural': '设计师',
                'ordering': ('-rating', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=120, verbose_name='商品名称')),
                ('category', models.CharField(choices=[('sofa', '沙发'), ('bed', '床'), ('table', '桌椅'), ('cabinet', '柜类'), ('light', '灯具'), ('appliance', '家电'), ('material', '建材'), ('decor', '软装')], max_length=20, verbose_name='品类')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='型号')),
                ('spec', models.CharField(blank=True, max_length=120, verbose_name='规格')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='适配风格')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='参考价(元)')),
                ('buy_url', models.URLField(blank=True, verbose_name='购买链接')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture/', verbose_name='商品图')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '家具商品',
                'verbose_name_plural': '家具商品',
                'ordering': ('category', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='配置名')),
                ('api_base', models.CharField(blank=True, help_text='OpenAI 兼容端点，如 https://api.openai.com/v1', max_length=300, verbose_name='API Base URL')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API Key')),
                ('model', models.CharField(blank=True, default='gpt-image-1', max_length=100, verbose_name='模型名')),
                ('image_size', models.CharField(blank=True, default='1024x1024', max_length=20, verbose_name='图像尺寸')),
                ('prompt_template', models.TextField(blank=True, default='将这张毛坯房照片重新渲染为{style}风格的{room_type}装修效果图，预算档位：{budget_tier}。要求：{requirement}。保持原始户型结构、门窗和墙体位置不变，仅添加装修、家具与软装，效果写实。', verbose_name='提示词模板')),
                ('enabled', models.BooleanField(default=False, help_text='未启用时使用占位图，便于无 Key 情况下跑通链路', verbose_name='启用真实调用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成配置',
                'verbose_name_plural': '生成配置',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='raw_photo',
            field=models.ImageField(blank=True, null=True, upload_to='raw_photos/', verbose_name='毛坯照片'),
        ),
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('raw_photo', models.ImageField(upload_to='raw_photos/', verbose_name='毛坯照片')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='目标风格')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='空间类型')),
                ('budget_tier', models.CharField(blank=True, max_length=10, verbose_name='预算档位')),
                ('requirement', models.TextField(blank=True, verbose_name='需求描述')),
                ('prompt', models.TextField(blank=True, verbose_name='实际发送给模型的提示词')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='renders/', verbose_name='效果图')),
                ('result_image_url', models.URLField(blank=True, max_length=1000, verbose_name='效果图URL')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('running', '生成中'), ('success', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_jobs', to='design.serviceprovider', verbose_name='推荐施工队')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_jobs', to='design.designer', verbose_name='推荐设计师')),
                ('furnitures', models.ManyToManyField(blank=True, to='design.furniture', verbose_name='关联家具')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='design.project', verbose_name='房屋项目')),
            ],
            options={
                'verbose_name': '效果图任务',
                'verbose_name_plural': '效果图任务',
                'ordering': ('-created_at',),
            },
        ),
    ]
