# Generated by Django 5.0.6 on 2026-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_designer_furniture_generationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderjob',
            name='design_note',
            field=models.TextField(blank=True, help_text='大模型生成的装修设计说明 / 家具搭配理由', verbose_name='AI 设计说明'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='api_base',
            field=models.CharField(blank=True, help_text='OpenAI 兼容端点。DeepSeek 填 https://api.deepseek.com/v1', max_length=300, verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='enabled',
            field=models.BooleanField(default=False, help_text='未启用时仅生成占位图与规则文案；启用后调用大模型生成设计说明', verbose_name='启用真实调用'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='model',
            field=models.CharField(blank=True, default='deepseek-chat', help_text='文本模型（DeepSeek 无图像 API），如 deepseek-chat', max_length=100, verbose_name='模型名'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='prompt_template',
            field=models.TextField(blank=True, default='你是资深室内设计师。请为一间{room_type}给出{style}风格、预算档位「{budget_tier}」的装修设计说明。用户需求：{requirement}。请输出：1) 整体设计思路；2) 空间布局与色彩建议；3) 推荐家具与软装搭配理由；4) 施工与预算提示。语言简洁专业，使用中文，分点表述。', verbose_name='提示词模板'),
        ),
    ]
