# Generated by Django 5.0.6 on 2026-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_renderjob_design_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconfig',
            name='image_api_base',
            field=models.CharField(blank=True, default='https://image.pollinations.ai', help_text='Pollinations 填 https://image.pollinations.ai', max_length=300, verbose_name='图像 API Base'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='image_api_key',
            field=models.CharField(blank=True, help_text='Pollinations 免费无需填写；OpenAI 兼容端点需填', max_length=300, verbose_name='图像 API Key'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='image_enabled',
            field=models.BooleanField(default=False, help_text='启用后调用下方图像端点生成真实效果图；关闭则用占位图', verbose_name='启用真实生图'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='image_model',
            field=models.CharField(blank=True, default='flux', help_text='Pollinations 可填 flux / turbo；OpenAI 填 gpt-image-1', max_length=100, verbose_name='图像模型'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='image_provider',
            field=models.CharField(blank=True, default='pollinations', help_text='pollinations（免费无Key）或 openai（需 image_api_key）', max_length=20, verbose_name='图像服务商'),
        ),
    ]
