# Generated by Django 5.0.6 on 2026-08-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_generationconfig_image_api_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.SlugField(help_text='前端提交用的稳定标识，如 lighting_soft', unique=True, verbose_name='模块编码')),
                ('name', models.CharField(max_length=60, verbose_name='模块名称')),
                ('group', models.CharField(choices=[('lighting', '灯光氛围'), ('material', '材质质感'), ('camera', '镜头视角'), ('color', '色彩基调'), ('layout', '布局收纳'), ('mood', '情绪风格'), ('quality', '画质控制')], max_length=20, verbose_name='所属分组')),
                ('description', models.CharField(blank=True, help_text='展示给用户的一句话说明', max_length=200, verbose_name='模块说明')),
                ('prompt_fragment', models.TextField(help_text='拼接进图像 prompt 的英文片段，如 soft diffused lighting, warm ambient glow', verbose_name='提示词片段')),
                ('negative_fragment', models.CharField(blank=True, help_text='需要规避的内容，如 harsh shadows', max_length=300, verbose_name='负向片段')),
                ('note_fragment', models.CharField(blank=True, help_text='拼进设计说明提示词的中文补充要求', max_length=200, verbose_name='设计说明补充')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='数值越小越靠前拼接', verbose_name='权重')),
                ('is_default', models.BooleanField(default=False, help_text='用户未选择任何模块时自动生效', verbose_name='默认启用')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('applies_to_room_types', models.JSONField(blank=True, default=list, help_text='为空表示全部空间适用，如 ["客厅","餐厅"]', verbose_name='限定空间')),
                ('applies_to_styles', models.JSONField(blank=True, default=list, help_text='为空表示全部风格适用', verbose_name='限定风格')),
            ],
            options={
                'verbose_name': 'Prompt 控制模块',
                'verbose_name_plural': 'Prompt 控制模块',
                'ordering': ('group', 'weight', 'id'),
            },
        ),
        migrations.AddField(
            model_name='renderjob',
            name='negative_prompt',
            field=models.TextField(blank=True, verbose_name='负向提示词'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='image_api_base',
            field=models.CharField(blank=True, default='https://image.pollinations.ai', help_text='MaiziAI 填 https://www.maizitech.xyz/v1；Pollinations 填 https://image.pollinations.ai', max_length=300, verbose_name='图像 API Base'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='image_model',
            field=models.CharField(blank=True, default='flux', help_text='MaiziAI 推荐 gpt-image-2-official；Pollinations 可填 flux / turbo', max_length=100, verbose_name='图像模型'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='image_provider',
            field=models.CharField(blank=True, default='pollinations', help_text='maizi（MaiziAI 异步生图，需Key）/ pollinations（免费无Key）/ openai（需Key）', max_length=20, verbose_name='图像服务商'),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='prompt_modules',
            field=models.ManyToManyField(blank=True, related_name='render_jobs', to='design.promptmodule', verbose_name='生效的控制模块'),
        ),
    ]
