# Generated by Django 5.0.6 on 2026-08-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_promptmodule_renderjob_negative_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='工作流名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_default', models.BooleanField(default=False, help_text='任务未指定工作流时使用；只应有一个默认', verbose_name='默认工作流')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('stop_on_error', models.BooleanField(default=False, help_text='关闭时单步失败仅记录并跳过，继续后续步骤（推荐）', verbose_name='步骤失败即终止')),
            ],
            options={
                'verbose_name': '生图工作流',
                'verbose_name_plural': '生图工作流',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.AddField(
            model_name='renderjob',
            name='workflow_log',
            field=models.JSONField(blank=True, default=list, help_text='每个步骤的状态、耗时与摘要', verbose_name='工作流执行日志'),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_jobs', to='design.renderworkflow', verbose_name='使用的工作流'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='执行顺序')),
                ('kind', models.CharField(choices=[('validate_input', '输入校验'), ('auto_orient', '按 EXIF 摆正'), ('resize_input', '缩放上传图'), ('enhance_input', '增强上传图(亮度/对比度/锐化)'), ('analyze_input', '分析上传图(亮度/色调/朝向)'), ('match_furniture', '匹配家具库'), ('build_prompt', '装配提示词(控制模块)'), ('append_prompt', '追加提示词片段'), ('generate_image', '调用生图'), ('postprocess', '成图调色(亮度/对比度/饱和度/锐化)'), ('resize_output', '缩放成图'), ('watermark', '添加水印'), ('design_note', '生成设计说明'), ('match_provider', '匹配施工队/设计师')], max_length=30, verbose_name='步骤类型')),
                ('name', models.CharField(blank=True, help_text='留空则用步骤类型名', max_length=80, verbose_name='步骤名称')),
                ('params', models.JSONField(blank=True, default=dict, help_text='该步骤的配置，见 admin 说明；填 {} 用默认值', verbose_name='参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('continue_on_error', models.BooleanField(default=True, help_text='勾选时该步骤报错只记录日志并跳过', verbose_name='本步失败仍继续')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='design.renderworkflow', verbose_name='所属工作流')),
            ],
            options={
                'verbose_name': '工作流步骤',
                'verbose_name_plural': '工作流步骤',
                'ordering': ('workflow', 'order', 'id'),
            },
        ),
    ]
