# Generated by Django 5.0.6 on 2026-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_alter_workflowstep_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='rooms',
            field=models.JSONField(blank=True, default=list, help_text='如 ["客厅","餐厅"]；留空表示不限空间。生图时按此过滤，避免客厅出现衣柜这类错配', verbose_name='适用空间'),
        ),
    ]
