# Generated by Django 5.0.6 on 2026-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_furniture_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('community', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='意向空间')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='意向风格')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算下限(元)')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算上限(元)')),
                ('requirement', models.TextField(blank=True, verbose_name='需求描述')),
                ('status', models.CharField(choices=[('new', '待跟进'), ('contacted', '已联系'), ('closed', '已关闭')], default='new', max_length=10, verbose_name='跟进状态')),
            ],
            options={
                'verbose_name': '用户需求收集',
                'verbose_name_plural': '用户需求收集',
                'ordering': ('-created_at',),
            },
        ),
    ]
