# Generated by Django 5.0.6 on 2026-08-17 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_customerrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_projects', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='HomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='报告名称')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='空间类型')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='目标风格')),
                ('budget_tier', models.CharField(blank=True, max_length=10, verbose_name='预算档位')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='报告内容')),
                ('status', models.CharField(choices=[('saved', '已保存'), ('ordered', '已下单')], default='saved', max_length=10, verbose_name='报告状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_reports', to='design.project', verbose_name='房屋项目')),
                ('render_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_reports', to='design.renderjob', verbose_name='生成任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '我的家报告书',
                'verbose_name_plural': '我的家报告书',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HomeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='订单名称')),
                ('amount_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算下限(元)')),
                ('amount_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='预算上限(元)')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='订单快照')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='订单状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_orders', to='design.project', verbose_name='房屋项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_orders', to='design.homereport', verbose_name='关联报告')),
            ],
            options={
                'verbose_name': '我的家项目订单',
                'verbose_name_plural': '我的家项目订单',
                'ordering': ('-created_at',),
            },
        ),
    ]
