# Generated by Django 5.0.6 on 2026-08-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_project_user_homereport_homeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='客户姓名'),
        ),
        migrations.AddField(
            model_name='homeorder',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='客户电话'),
        ),
        migrations.AddField(
            model_name='homeorder',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='[{name, category, price, quantity, amount}]', verbose_name='订单明细'),
        ),
        migrations.AddField(
            model_name='homeorder',
            name='order_no',
            field=models.CharField(blank=True, editable=False, help_text='系统自动生成，如 HD20260817123000A1B2C3', max_length=32, unique=True, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='homeorder',
            name='remark',
            field=models.TextField(blank=True, verbose_name='客户备注'),
        ),
        migrations.AddField(
            model_name='homeorder',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='订单总价(元)'),
        ),
        migrations.AlterField(
            model_name='homeorder',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('paid', '已支付'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='订单状态'),
        ),
    ]
