# Generated by Django 5.0.6 on 2026-08-17 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_homeorder_customer_name_homeorder_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('intention_images', models.JSONField(blank=True, default=list, help_text='图片 URL 列表：包含户型图、客户上传的原始照片、生成的效果图等', verbose_name='客户意向图')),
                ('design_advice', models.TextField(blank=True, verbose_name='家装建议')),
                ('furniture_snapshot', models.JSONField(blank=True, default=list, help_text='同步自前端报告或订单明细，如 [{name, category, price, quantity}]', verbose_name='家具清单')),
                ('designer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='设计师')),
                ('contractor_snapshot', models.JSONField(blank=True, default=dict, verbose_name='服务商/施工队')),
                ('report_snapshot', models.JSONField(blank=True, default=dict, verbose_name='前端报告快照')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='design.homeorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'ordering': ('-created_at',),
            },
        ),
    ]
