# Generated by Django 5.0.6 on 2026-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_images',
            field=models.JSONField(blank=True, default=list, help_text='户型图、客户上传的原始照片等图片 URL 列表', verbose_name='客户上传图片'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='generated_images',
            field=models.JSONField(blank=True, default=list, help_text='效果图生成任务产出的图片 URL 列表', verbose_name='AI 生成图片'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='contractor_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='装修队/服务商'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='furniture_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='同步自前端报告或订单明细，如 [{name, category, price, quantity, buy_url, image_url}]', verbose_name='家具清单'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='intention_images',
            field=models.JSONField(blank=True, default=list, help_text='客户上传图片与 AI 生成图片的合并列表，便于快速浏览', verbose_name='意向图汇总'),
        ),
    ]
