# Generated by Django 5.0.6 on 2026-08-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_orderdetail_customer_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renderworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_workflows', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='renderworkflow',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='由创建者打标签，如 ["客厅","现代简约","品质","图生图"]；AI 生图时会根据空间/风格/预算档位自动匹配', verbose_name='分类标签'),
        ),
        migrations.AlterField(
            model_name='renderworkflow',
            name='is_default',
            field=models.BooleanField(default=False, help_text='无标签匹配且未指定工作流时使用；只应有一个默认', verbose_name='默认工作流'),
        ),
    ]
