# Generated by Django 5.0.6 on 2026-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_renderworkflow_created_by_renderworkflow_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='kind',
            field=models.CharField(choices=[('validate_input', '输入校验'), ('auto_orient', '按 EXIF 摆正'), ('resize_input', '缩放上传图'), ('enhance_input', '增强上传图(亮度/对比度/锐化)'), ('analyze_input', '分析上传图(亮度/色调/朝向)'), ('mark_doors', '标记门洞(禁止摆放家具)'), ('match_furniture', '匹配家具库'), ('build_prompt', '装配提示词(控制模块)'), ('append_prompt', '追加提示词片段'), ('generate_image', '调用生图'), ('edit_image', '图生图(以上传照片为参考图)'), ('postprocess', '成图调色(亮度/对比度/饱和度/锐化)'), ('resize_output', '缩放成图'), ('watermark', '添加水印'), ('design_note', '生成设计说明'), ('match_provider', '匹配施工队/设计师')], max_length=30, verbose_name='步骤类型'),
        ),
    ]
