# Generated by Django 5.0.6 on 2026-08-19 06:26

from urllib.parse import urlparse

from django.db import migrations


def _to_relative_media_url(value):
    """把历史快照里带 Host 的 /media/ 图片地址改成站点相对路径。

    旧版 FurnitureSerializer 会把图片拼成 http://localhost:8000/media/...，
    该地址在换域名 / 内网访问时会 404。这里只处理路径以 /media/ 开头的
    绝对地址，不影响购买链接等外部 URL。
    """
    if isinstance(value, dict):
        return {key: _to_relative_media_url(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_to_relative_media_url(item) for item in value]
    if isinstance(value, str):
        parsed = urlparse(value)
        if parsed.scheme in ('http', 'https') and parsed.path.startswith('/media/'):
            return parsed.path + (('?' + parsed.query) if parsed.query else '')
    return value


def normalize_media_urls(apps, schema_editor):
    HomeReport = apps.get_model('design', 'HomeReport')
    HomeOrder = apps.get_model('design', 'HomeOrder')
    OrderDetail = apps.get_model('design', 'OrderDetail')

    for report in HomeReport.objects.all():
        if isinstance(report.report, dict):
            report.report = _to_relative_media_url(report.report)
            report.save(update_fields=['report', 'updated_at'])

    for order in HomeOrder.objects.all():
        if isinstance(order.payload, dict):
            order.payload = _to_relative_media_url(order.payload)
            order.save(update_fields=['payload', 'updated_at'])

    for detail in OrderDetail.objects.all():
        detail.intention_images = _to_relative_media_url(detail.intention_images)
        detail.customer_images = _to_relative_media_url(detail.customer_images)
        detail.generated_images = _to_relative_media_url(detail.generated_images)
        detail.furniture_snapshot = _to_relative_media_url(detail.furniture_snapshot)
        detail.report_snapshot = _to_relative_media_url(detail.report_snapshot)
        detail.save(update_fields=[
            'intention_images', 'customer_images', 'generated_images',
            'furniture_snapshot', 'report_snapshot', 'updated_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_alter_workflowstep_kind'),
    ]

    operations = [
        migrations.RunPython(normalize_media_urls, migrations.RunPython.noop),
    ]
