# Generated by Django 5.2.17 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_customerrequirement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconfig',
            name='talkbot_api_base',
            field=models.CharField(blank=True, default='https://api.deepseek.com', help_text='必须使用 HTTPS；DeepSeek 官方地址：https://api.deepseek.com', max_length=300, verbose_name='机器人 API Base URL'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='talkbot_api_key_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='机器人 API Key（密文）'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='talkbot_enabled',
            field=models.BooleanField(default=False, help_text='启用后 TalkBot 调用下方文本模型；未配置或调用失败时自动回退规则回复', verbose_name='启用谈单机器人 API'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='talkbot_model',
            field=models.CharField(blank=True, default='deepseek-v4-flash', help_text='例如 deepseek-v4-flash 或 deepseek-v4-pro', max_length=100, verbose_name='机器人模型名'),
        ),
    ]
